name: wisburg_design_tokens
description: Internal design tokens for Wisburg Flutter applications. Not for public use.
version: 1.0.2
homepage: https://github.com/royorange/design-tokens
repository: https://github.com/royorange/design-tokens/tree/main/packages/flutter

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
