// Generated by Design Tokens - DO NOT EDIT
// Last updated: 2025-07-18T17:29:17.439Z

import 'package:flutter/material.dart';

/// 颜色常量定义
class AppColors {

  // Primary Colors
  static const Color primary50 = Color(0xFFEAEAFD);
  static const Color primary100 = Color(0xFFCBC9F8);
  static const Color primary200 = Color(0xFFA7A7F4);
  static const Color primary300 = Color(0xFF8283F0);
  static const Color primary400 = Color(0xFF6765EC);
  static const Color primary500 = Color(0xFF4F46E5);
  static const Color primary600 = Color(0xFF493DD9);
  static const Color primary700 = Color(0xFF4031CD);
  static const Color primary800 = Color(0xFF3923C1);
  static const Color primary900 = Color(0xFF2B00B0);

  // Neutral Colors
  static const Color neutral50 = Color(0xFFE9EBEE);
  static const Color neutral100 = Color(0xFFD3D4D8);
  static const Color neutral200 = Color(0xFFB6B8C0);
  static const Color neutral300 = Color(0xFF999BA8);
  static const Color neutral400 = Color(0xFF838696);
  static const Color neutral500 = Color(0xFF6E7285);
  static const Color neutral600 = Color(0xFF606374);
  static const Color neutral700 = Color(0xFF454650);
  static const Color neutral800 = Color(0xFF202029);
  static const Color neutral900 = Color(0xFF121212);
  static const Color white = Color(0xFFFFFFFF);
  static const Color black = Color(0xFF000000);

  // Error Colors
  static const Color error50 = Color(0xFFFEF2F2);
  static const Color error100 = Color(0xFFFEE2E2);
  static const Color error200 = Color(0xFFFECACA);
  static const Color error300 = Color(0xFFFCA5A5);
  static const Color error400 = Color(0xFFF87171);
  static const Color error500 = Color(0xFFEF4444);
  static const Color error600 = Color(0xFFDC2626);
  static const Color error700 = Color(0xFFB91C1C);
  static const Color error800 = Color(0xFF991B1B);
  static const Color error900 = Color(0xFF7F1D1D);
}

/// 间距常量定义
class AppSpacing {
  static const double spacing0 = 0.0;
  static const double spacing1 = 4.0;
  static const double spacing2 = 8.0;
  static const double spacing3 = 12.0;
  static const double spacing4 = 16.0;
  static const double spacing5 = 20.0;
  static const double spacing6 = 24.0;
  static const double spacing8 = 32.0;
  static const double spacing10 = 40.0;
  static const double spacing12 = 48.0;
  static const double spacing16 = 64.0;
}

/// 圆角常量定义
class AppRadius {
  static const double none = 0.0;
  static const double sm = 4.0;
  static const double md = 8.0;
  static const double lg = 12.0;
  static const double xl = 16.0;
  static const double full = 9999.0;
}

/// 字体大小常量定义
class AppFontSizes {
  static const double xs = 12.0;
  static const double sm = 14.0;
  static const double base = 16.0;
  static const double lg = 18.0;
  static const double xl = 20.0;
  static const double size2xl = 24.0;
  static const double size3xl = 30.0;
  static const double size4xl = 36.0;
}

/// 语义化颜色 Theme Extension
@immutable
class AppColorsExtension extends ThemeExtension<AppColorsExtension> {
  const AppColorsExtension({
    required this.backgroundBase,
    required this.backgroundElevated,
    required this.textPrimary,
    required this.textSecondary,
    required this.textDisabled,
    required this.borderDefault,
    required this.borderFocus,
  });

  final Color backgroundBase;
  final Color backgroundElevated;
  final Color textPrimary;
  final Color textSecondary;
  final Color textDisabled;
  final Color borderDefault;
  final Color borderFocus;

  @override
  AppColorsExtension copyWith({
    Color? backgroundBase,
    Color? backgroundElevated,
    Color? textPrimary,
    Color? textSecondary,
    Color? textDisabled,
    Color? borderDefault,
    Color? borderFocus,
  }) {
    return AppColorsExtension(
      backgroundBase: backgroundBase ?? this.backgroundBase,
      backgroundElevated: backgroundElevated ?? this.backgroundElevated,
      textPrimary: textPrimary ?? this.textPrimary,
      textSecondary: textSecondary ?? this.textSecondary,
      textDisabled: textDisabled ?? this.textDisabled,
      borderDefault: borderDefault ?? this.borderDefault,
      borderFocus: borderFocus ?? this.borderFocus,
    );
  }

  @override
  AppColorsExtension lerp(ThemeExtension<AppColorsExtension>? other, double t) {
    if (other is! AppColorsExtension) {
      return this;
    }
    return AppColorsExtension(
      backgroundBase: Color.lerp(backgroundBase, other.backgroundBase, t)!,
      backgroundElevated: Color.lerp(backgroundElevated, other.backgroundElevated, t)!,
      textPrimary: Color.lerp(textPrimary, other.textPrimary, t)!,
      textSecondary: Color.lerp(textSecondary, other.textSecondary, t)!,
      textDisabled: Color.lerp(textDisabled, other.textDisabled, t)!,
      borderDefault: Color.lerp(borderDefault, other.borderDefault, t)!,
      borderFocus: Color.lerp(borderFocus, other.borderFocus, t)!,
    );
  }

  /// Light theme colors
  static const light = AppColorsExtension(
    backgroundBase: AppColors.white,
    backgroundElevated: AppColors.neutral50,
    textPrimary: AppColors.neutral900,
    textSecondary: AppColors.neutral700,
    textDisabled: AppColors.neutral400,
    borderDefault: AppColors.neutral300,
    borderFocus: AppColors.primary500,
  );

  /// Dark theme colors
  static const dark = AppColorsExtension(
    backgroundBase: AppColors.neutral900,
    backgroundElevated: AppColors.neutral800,
    textPrimary: AppColors.white,
    textSecondary: AppColors.neutral300,
    textDisabled: AppColors.neutral600,
    borderDefault: AppColors.neutral700,
    borderFocus: AppColors.primary400,
  );
}

/// 组件级别 Tokens
class ButtonTokens {
  const ButtonTokens({
    required this.primaryBackground,
    required this.primaryText,
    required this.primaryBackgroundHover,
    required this.paddingX,
    required this.paddingY,
    required this.radius,
  });

  final Color primaryBackground;
  final Color primaryText;
  final Color primaryBackgroundHover;
  final double paddingX;
  final double paddingY;
  final double radius;

  static const light = ButtonTokens(
    primaryBackground: AppColors.primary500,
    primaryBackgroundHover: AppColors.primary600,
    primaryText: AppColors.white,
    paddingX: AppSpacing.spacing4,
    paddingY: AppSpacing.spacing3,
    radius: AppRadius.md,
  );

  static const dark = ButtonTokens(
    primaryBackground: AppColors.primary500,
    primaryBackgroundHover: AppColors.primary400,
    primaryText: AppColors.white,
    paddingX: AppSpacing.spacing4,
    paddingY: AppSpacing.spacing3,
    radius: AppRadius.md,
  );
}

/// Material 3 ColorScheme definitions
class AppColorSchemes {
  static const ColorScheme lightColorScheme = ColorScheme(
    brightness: Brightness.light,
    primary: AppColors.primary500,
    onPrimary: AppColors.white,
    primaryContainer: AppColors.primary100,
    onPrimaryContainer: AppColors.primary900,
    secondary: AppColors.primary400,
    onSecondary: AppColors.white,
    secondaryContainer: AppColors.primary100,
    onSecondaryContainer: AppColors.primary900,
    error: AppColors.error600,
    onError: AppColors.white,
    errorContainer: AppColors.error50,
    onErrorContainer: AppColors.error900,
    surface: AppColors.white,
    onSurface: AppColors.neutral900,
    surfaceContainerHighest: AppColors.neutral100,
    onSurfaceVariant: AppColors.neutral700,
    outline: AppColors.neutral400,
    outlineVariant: AppColors.neutral300,
    shadow: AppColors.black,
    scrim: AppColors.black,
    inverseSurface: AppColors.neutral900,
    onInverseSurface: AppColors.white,
    inversePrimary: AppColors.primary300,
  );

  static const ColorScheme darkColorScheme = ColorScheme(
    brightness: Brightness.dark,
    primary: AppColors.primary400,
    onPrimary: AppColors.primary900,
    primaryContainer: AppColors.primary700,
    onPrimaryContainer: AppColors.primary100,
    secondary: AppColors.primary300,
    onSecondary: AppColors.primary900,
    secondaryContainer: AppColors.primary700,
    onSecondaryContainer: AppColors.primary100,
    error: AppColors.error500,
    onError: AppColors.white,
    errorContainer: AppColors.error800,
    onErrorContainer: AppColors.error200,
    surface: AppColors.neutral900,
    onSurface: AppColors.neutral100,
    surfaceContainerHighest: AppColors.neutral800,
    onSurfaceVariant: AppColors.neutral300,
    outline: AppColors.neutral600,
    outlineVariant: AppColors.neutral700,
    shadow: AppColors.black,
    scrim: AppColors.black,
    inverseSurface: AppColors.neutral100,
    onInverseSurface: AppColors.neutral900,
    inversePrimary: AppColors.primary600,
  );
}

/// Design Tokens 直接访问
class DesignTokens {
  // Private constructor to prevent instantiation
  DesignTokens._();

  // Token collections
  static const colors = AppColors;
  static const spacing = AppSpacing;
  static const radius = AppRadius;
  static const fontSize = AppFontSizes;
  static const colorSchemes = AppColorSchemes;

  // Component tokens
  static const lightButtonTokens = ButtonTokens.light;
  static const darkButtonTokens = ButtonTokens.dark;
}
