// Generated by Design Tokens - DO NOT EDIT
// Last updated: 2025-07-18T17:22:21.235Z

import 'package:flutter/material.dart';

/// 颜色常量定义
class AppColors {
}

/// 间距常量定义
class AppSpacing {
}

/// 圆角常量定义
class AppRadius {
}

/// 字体大小常量定义
class AppFontSizes {
}

/// 语义化颜色 Theme Extension
@immutable
class AppColorsExtension extends ThemeExtension<AppColorsExtension> {
  const AppColorsExtension({
  });


  @override
  AppColorsExtension copyWith({
  }) {
    return AppColorsExtension(
    );
  }

  @override
  AppColorsExtension lerp(ThemeExtension<AppColorsExtension>? other, double t) {
    if (other is! AppColorsExtension) {
      return this;
    }
    return AppColorsExtension(
    );
  }

  /// Light theme colors
  static const light = AppColorsExtension(
  );

  /// Dark theme colors
  static const dark = AppColorsExtension(
  );
}

/// 组件级别 Tokens

/// Material 3 ColorScheme definitions
class AppColorSchemes {
  static const ColorScheme lightColorScheme = ColorScheme(
    brightness: Brightness.light,
    primary: AppColors.primary500,
    onPrimary: AppColors.white,
    primaryContainer: AppColors.primary100,
    onPrimaryContainer: AppColors.primary900,
    secondary: AppColors.primary400,
    onSecondary: AppColors.white,
    secondaryContainer: AppColors.primary100,
    onSecondaryContainer: AppColors.primary900,
    error: AppColors.error600,
    onError: AppColors.white,
    errorContainer: AppColors.error50,
    onErrorContainer: AppColors.error900,
    surface: AppColors.white,
    onSurface: AppColors.neutral900,
    surfaceContainerHighest: AppColors.neutral100,
    onSurfaceVariant: AppColors.neutral700,
    outline: AppColors.neutral400,
    outlineVariant: AppColors.neutral300,
    shadow: AppColors.black,
    scrim: AppColors.black,
    inverseSurface: AppColors.neutral900,
    onInverseSurface: AppColors.white,
    inversePrimary: AppColors.primary300,
  );

  static const ColorScheme darkColorScheme = ColorScheme(
    brightness: Brightness.dark,
    primary: AppColors.primary400,
    onPrimary: AppColors.primary900,
    primaryContainer: AppColors.primary700,
    onPrimaryContainer: AppColors.primary100,
    secondary: AppColors.primary300,
    onSecondary: AppColors.primary900,
    secondaryContainer: AppColors.primary700,
    onSecondaryContainer: AppColors.primary100,
    error: AppColors.error500,
    onError: AppColors.white,
    errorContainer: AppColors.error800,
    onErrorContainer: AppColors.error200,
    surface: AppColors.neutral900,
    onSurface: AppColors.neutral100,
    surfaceContainerHighest: AppColors.neutral800,
    onSurfaceVariant: AppColors.neutral300,
    outline: AppColors.neutral600,
    outlineVariant: AppColors.neutral700,
    shadow: AppColors.black,
    scrim: AppColors.black,
    inverseSurface: AppColors.neutral100,
    onInverseSurface: AppColors.neutral900,
    inversePrimary: AppColors.primary600,
  );
}

/// Design Tokens 直接访问
class DesignTokens {
  // Private constructor to prevent instantiation
  DesignTokens._();

  // Token collections
  static const colors = AppColors;
  static const spacing = AppSpacing;
  static const radius = AppRadius;
  static const fontSize = AppFontSizes;
  static const colorSchemes = AppColorSchemes;

  // Component tokens
}
